- convert.py
- library/exportall.py
- library/exportarxml.py
- library/exportsym.py
- library/importkcd.py
This is small, but it's a first pull request.  I am working on the tests as well.
> Minor adjustments for new exportSym support

- canmatrix/exportdbf.py
- canmatrix/importdbf.py
@altendky: I think, you are right. The 'ints' only force python to handle the variables as numbers (instead of strings)
By the way: this pull-request is from master to byteorder-branch...
> pull master changes

- canmatrix/exportcsv.py
This also addresses any newline character problems and other issues.
> Use python's csv module to export to csv.

- canmatrix/exportkcd.py
- canmatrix/importkcd.py
#46 fixed code. For some reason Atom decided to strip trailing white space in importkcd which is why it shows so many changes.
> Fixed little-endian big-endian problem

- canmatrix/exportkcd.py
minor fixes for kcd export.
remove trailing zero's in min/max, remove empty tags, remove max=0.
> kcd minor conversion fixes

- canmatrix/canmatrix.py
shows the names of frames/signals in the list for better debug when using IDE like pycharm
> Better debug

- canmatrix/exportkcd.py
bugfix in signal attribute to kcd notes.  use int for index into type enums array.
> bugfix in signal attribute to kcd notes conversion

- canmatrix/convert.py
- canmatrix/exportany.py
- canmatrix/exportxls.py
The `exportany` function should basically be the counter-part to `importany`.
Also fixed an issue with xls export from my last pull request.
> Add exportany function

- canmatrix/arxml.py
Signed-off-by: Guillaume Ranquet <guillaume.ranquet@renault.com>
> Fixup some issues with arxml4.2 integration

- canmatrix/arxml.py
- canmatrix/canmatrix.py
Followed OSEK (ISO-17356)
Tested with ARXML -> DBC conversion
Signed-of-by: Guillaume Ranquet <guillaume.ranquet@renault.com>
> Fixup motorola/intel endianness

- canmatrix/formats.py
Simply try to get the same features to loadp as to loads function in canmatrix.formats. Renamed a variable in the function to improve readability of the code.
> loadp function supports flatImport and key

- setup.py
Encoding/Decoding feature requires bitstruct
> Adding `codec` extra requirement

- canmatrix/sym.py
… dumped file) for compatibility with PCAN Symbol Editor
> (Issue #139) sym dump : change ID to a short format if type is not extended

- canmatrix/arxml.py
- canmatrix/canmatrix.py
- test/test.arxml
> Use float_factory (iow, Decimal) for arxml signal size

- src/canmatrix/canmatrix.py
- src/canmatrix/sym.py
- src/canmatrix/tests/test_sym.py
> Error for colliding mux ids when loading .sym

- .idea/coverage.bat
batch file to provide coverage report locally from IDE.
Simply define it as an external tool (in PyCharm), select test module or single file and run the tool.
Arguments: $PyInterpreterDirectory$ $FilePath$
Working directory: $ProjectFileDir$
> Add batch file for coverage from IDE

- src/canmatrix/canmatrix.py
- src/canmatrix/cmjson.py
- src/canmatrix/compare.py
- src/canmatrix/copy.py
- src/canmatrix/sym.py
- src/canmatrix/xls_common.py
As promissed, I unified the signature of attribute() functions.
Added docstrings to canmatrix.py.
Fixed few typos.
Add some remarks (comments ending with question mark)
Sorry to mix again these change types but it was single-pass work. I still believe it's reviewable, I strongly talked to my fingers not to do _all_ they wanted to :-) . I hope it helps to increase the code lucidity.
Thx for review.
> Update attribute() signature and add/update some docstrings.

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
Use attr in SignalGroup. Add tests.
I propose to access signals by [] operator as well.
Thank you for review.
> attr.ibify SignalGroup

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
attr.ibify BoardUnit. Add UTs.
> attr.ibify BoardUnit.

- requirements.test.py2.txt
- requirements.test.py3.txt
- setup.py
- src/canmatrix/canmatrix.py
> Just depend on bitstruct

- src/canmatrix/canmatrix.py
As discussed in PR #202 I changed all docstrings of functions which uses 'glob pattern' to explicitely mention it. I also reverted attribute names back to `globSignal` & `globFrame`. No code-logic change is included in this PR.
Thank you.
> Update 'glob' docstrings

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
I added some Signal tests and fixed two docstrings (problems found when writing tests).
What is your opiniton on TODO question in test_signal_set_startbit_raise()?
> Add Signal tests

- src/canmatrix/tests/test_cmjson.py
> Add json output test for long signal names

- requirements.test.py3.txt
- setup.py
- src/canmatrix/dbc.py
- src/canmatrix/tests/test_dbc.py
@altendky 
i pulled your pr to my git (don't know if this was the correct way to do it)
changed to the expected behavior described in #230 
reading dbc with long names should already work with this pr
> [WIP] dbc test long signal names import

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
* Regression Frame tests for the obvious functionality
* try to resolve problems found:
* fix J1939 getter/setter (probably leftover after introducing attrs?)
* fix attribute() 'default' value (introduced by me :-( )
* Improve two docstrings.
Thanks for review!
> [WIP] 'Simple' Frame tests and fixes

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
Simple tests for define. I don't know what is expected behaviour of `HEX`, but it seems suspicious that it behaves like `INT`. Can I check it somehow/somewhere? Is it based on DBC, or an another format?
> Tests for 'Define'

- src/canmatrix/sym.py
- src/canmatrix/tests/test_sym.py
> Prevent truncation of .sym file long names

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
> Make Signal min/max defaults respect calc_xxx_for_none flags.

- src/canmatrix/sym.py
- src/canmatrix/tests/test_sym.py
> Fix and test for double in .sym

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
I don't know what is the status of DecodedSignal class but I (or rather the IDE) remarked there is mix of @attr.s and `__init__()`  and mistake in attribute names, plus misplaced docstring. Feel free to reject the PR if you have better version somewhere in branch.
> Correct and test DecodedSignal

- src/canmatrix/compare.py
This is probably bad in more ways but here's a quick attempt at a fix.
#ebroecker/canmatrix#272
> Fix unicode type check

- src/canmatrix/arxml.py
- src/canmatrix/tests/test_utils.py
- src/canmatrix/utils.py
* make guess_value compatible to py2
* ignore frames without arbitration id while reading arxml
> [WIP] - Iss277 - fix arxml issue

- src/canmatrix/arxml.py
- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
rename frame.receiver in frame.receivers
> [WIP] Iss280: rename frame.receiver in frame.receivers

- src/canmatrix/dbc.py
- src/canmatrix/tests/test_dbc.py
> [WIP] let dbc replace not known attibute-defines by STRING #281

- src/canmatrix/canmatrix.py
- src/canmatrix/convert.py
- src/canmatrix/copy.py
- src/canmatrix/dbc.py
- src/canmatrix/dbf.py
add support for signals which are not contained by a frame but directly by matrix
>  [WIP] add flat signals to canmatrix and copy option to copy them (#93)

- src/canmatrix/join.py
- snake_case
- redundant parenthesis
> Resolve inspection issues in 'join' module.

- src/canmatrix/cancluster.py
- src/canmatrix/formats/kcd.py
- Upper case class name
- Snake case variables
- Define used instance variables in `__init__`
- Annotate
> Tidy and annotate CanCluster

- examples/exampleMerge.py
- src/canmatrix/convert.py
- src/canmatrix/formats/__init__.py
- src/canmatrix/tests/test_cmjson.py
- src/canmatrix/tests/test_frame_decoding.py
- src/canmatrix/tests/test_frame_encoding.py
> Tidy 'formats' __init__

- src/canmatrix/utils.py
- code style cleanup
- add annotations
> Tidy utils module

- src/canmatrix/copy.py
- code style cleanup
- add annotations
- fix mypy detected issues (old attribute names)
For annotations I had to add kind of `import canmatrix` and got unresolvable dependency loop. I realized that the `from module import Class` tend to make such cycles if used frequently. 
@altendky please review this as well if you're ok with such import.
BTW do we need the `absolute_import`? It's for py < 2.7 , isn't it?
> Refactor 'copy' module

- mypy.ini
- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
- Annotate CanMatrix class
- Resolve some issues
- Add few tests to verify changed code
- Tune mypy config - just believe me that it's ok for now :)
> CanMatrix annotatios + some tests

- src/canmatrix/formats/yaml.py
- I hope the `yaml` belongs to `formats`
- Fix start_bit called on signal
- Resolve some Inspection findings
But there are multiple unresolved references in respect to current pyyaml version in pip@py3.
> Move yaml  to format

- requirements.test.py3.txt
- src/canmatrix/log.py
Annotate and cleanup log module
> Annotate log module

- README.md
- setup.py
For how it looks like see [the branch](https://github.com/Funth0mas/canmatrix/tree/pypi_shields#readme).
PyPi python version will hopefully work with the next release, because it's taken from setup.py
okay stop procrastination :-)
> Add some funny info shields to the README.

- src/canmatrix/compare.py
attr.ibify CompareResult in the module `compare`.
Make the memebers public (no underscore).
> Use attrs for CompareResult in compare module

- src/canmatrix/formats/cmcsv.py
- annotate all functions
- rename to snake_case
- shorten evaluation of the configuration dictionary
This is meant as the final "typing + codestyle" refactoring for this file. Any comments are welcome.
> Fine annotation and codestyle cleanup: CSV

- examples/decodeFrame.py
- examples/encodeFrame.py
- examples/exampleMerge.py
- src/canmatrix/formats/__init__.py
- src/canmatrix/tests/test_cmjson.py
- src/canmatrix/tests/test_frame_decoding.py
- src/canmatrix/tests/test_frame_encoding.py
Add and use 3 load*_flat() functions  instead of `flat_import` parameter (1st part of #339)
> Add dedicated formats.load_flat()

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/xlsx.py
Format xlsx
- finish annotation
- snake_case renaming
- try to fix some suspicious code like `type(var).__name__ != "float"` which was imho obsolete
I hope I did not break the code more than it already was.
> Annotation and cleanup xslx

- src/canmatrix/formats/fibex.py
- annotate fibex format
- codestyle cleanup
> annotate fibex format

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/sym.py
- annotations for `sym` module
- codestyle cleanup
- fix one occurence of #326
> Annotate sym format

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/dbf.py
- type annotations
- partial codestyle cleanup
> annotate dbf format

- src/canmatrix/formats/yaml.py
- basic annotation
- remove `cm` alias (not needed anymore)
> annotate yaml format

- MANIFEST.in
the conda-forge recipe needs the LICENSE file
> include LICENSE in source distribution

- src/canmatrix/formats/arxml.py
add ARXML-Support for Secured PDUs
> possible fix for #382 (support secured pdus)

- src/canmatrix/cli/convert.py
- src/canmatrix/formats/cmjson.py
- src/canmatrix/tests/test_cmjson.py
https://github.com/ebroecker/canmatrix/issues/379
> Dump factor, offset, min, max as float. Load as numeric

- src/canmatrix/cancluster.py
- src/canmatrix/canmatrix.py
- src/canmatrix/cli/compare.py
- src/canmatrix/cli/convert.py
- src/canmatrix/convert.py
- src/canmatrix/copy.py
- src/canmatrix/formats/__init__.py
- src/canmatrix/formats/arxml.py
- src/canmatrix/formats/dbc.py
- src/canmatrix/formats/kcd.py
- src/canmatrix/formats/scapy.py
- src/canmatrix/formats/xls.py
- src/canmatrix/formats/yaml.py
- clean redundant annotations (close #323)
- update annotations
- fix few typos
- remove "cm" alias
> Annotation cleanup

- src/canmatrix/formats/__init__.py
- src/canmatrix/formats/csv.py
- src/canmatrix/formats/json.py
- src/canmatrix/tests/test_json.py
> Remove cm prefix

- src/canmatrix/formats/scapy.py
- src/canmatrix/tests/test_scapy.py
@polybassa
could you have a look?
> [WIP] add muxing support to scapy output; merge PR #398 also

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/sym.py
- src/canmatrix/tests/test_sym.py
- src/canmatrix/tests/test_utils.py
- src/canmatrix/utils.py
> Process the .sym file "Title" field. fixes #469 And Fix Enum dictionary comma splitting 

- src/canmatrix/formats/json.py
- src/canmatrix/tests/test_json.py
Add a test to check that if a json file is read containing enums and
then saved and re-read it get the same enum table
> Add enumerations as a field to the json file to store the value tables

- src/canmatrix/formats/sym.py
- src/canmatrix/tests/test_sym.py
> Process type labels which are enumeration names

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/arxml.py
Update to read baudrate from arxml.
Should fix https://github.com/ebroecker/canmatrix/issues/448
> Arxml read baudrate

- src/canmatrix/formats/sym.py
- src/canmatrix/tests/test_sym.py
> Fix sym mux decode, by always treating mux field as unsigned

- src/canmatrix/canmatrix.py
If a complexly multiplexed signal has a sub-multiplexer with no values, a TypeError is thrown.
I ran into this while using [commaai/opendbc](https://github.com/commaai/opendbc) which muxes first on OBD-II service and then PID. They define a service 2 but do not enumerate any PIDs for it, causing the above referenced exception.
> src/canmatrix.py: fix nested mux with no values

- src/canmatrix/canmatrix.py
allow direct decoding of python-can messages
> add direct decode function for python can frames

- src/canmatrix/formats/dbc.py
- src/canmatrix/tests/test_dbc.py
Currently the initial_value is incorrectly set to the signal raw value.
> Set initial_value to physical value

- src/canmatrix/formats/arxml.py
170MB file parsing goes from 13 minutes to 3 minutes
fix ECU receivers/transmitters per cluster
> arxml CAN parsing optim and fixes

- src/canmatrix/canmatrix.py
Changing:
1. print error message
1. raise
To:
1. raise error message
> Remove prints from the code and add the message to the exception

- src/canmatrix/formats/dbc.py
- src/canmatrix/tests/test_dbc.py
- src/canmatrix/utils.py
dbc: cope with signals without receiver
> fix for issue #596

- src/canmatrix/formats/xls.py
- src/canmatrix/formats/xlsx.py
> #612 Bugfix formats.xls and formats.xlsx missing method parameters

- .travis.yml
- appveyor.yml
- setup.py
- tox.ini
fixes issue <https://github.com/danielhrisca/asammdf/issues/628>
> feat: add support for Python 3.10

- src/canmatrix/formats/fibex.py
Support Cycletime when converting dbc to fibex #627
> support cycle

- src/canmatrix/formats/fibex.py
> Support signal values in FIBEX

- src/canmatrix/canmatrix.py
This will fix #654, the rounding error
> Fix rounding error issue #654

- src/canmatrix/formats/arxml.py
just a few changes regarding logging to prevent confusing situations (Frame <-> Frame-Trigger)
> precise logging related to Frame/Frametrigger to avoid confusions

- src/canmatrix/convert.py
- src/canmatrix/formats/arxml.py
add pdu-name and can-frame-triggering-name to frame attributes during arxml read add option for convert to rename frame form frame.attribute
> arxml - pdu name

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
value-tables contain raw values
> fix for #671

- src/canmatrix/formats/json.py
- src/canmatrix/tests/test_json.py
> quick-fix for issue/pr #680

- src/canmatrix/formats/json.py
> add basic ecu info to json format

- docs/cli.rst
- src/canmatrix/canmatrix.py
- src/canmatrix/cli/convert.py
- src/canmatrix/convert.py
- src/canmatrix/tests/test_canmatrix.py
> add feature to compress frame

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/json.py
Hi Ed,
I noticed the message attributes were not being loaded for jsons. Here is a fix for that.
Russ
> fix: load json attributes from each message

- src/canmatrix/formats/arxml.py
This tries to fix an issue where the PDU is `None` (e.g., because the frame doesn't have a PDU), and the selector is searching for `//I-SIGNAL-TO-I-PDU-MAPPING` from the root of `Earxml`.
https://github.com/ebroecker/canmatrix/blob/2eb27ec433a71ca7e563d13d344cef60821e9cfe/src/canmatrix/formats/arxml.py#L1633-L1635
> Don't get I-SIGNAL-TO-I-PDU-MAPPING when PDU is None.

- src/canmatrix/formats/fibex.py
@ebroecker could you please review ?
> Support default values for fibex signals (#731)

- src/canmatrix/formats/fibex.py
Adding support to write multiplexed PDUs to FIBEX.
> Fibex mux support

- src/canmatrix/formats/fibex.py
@LarsVoelker , I think we have missed adding a shortname for the static part.
@ebroecker, could you please check this PR and merge it ?
> add missing shortname for static_part

- src/canmatrix/formats/fibex.py
Fixing the broken static signals
> fix wrong signal id for static signals

- src/canmatrix/utils.py
Support to decode infinity value in utils
> Support to decode infinity value

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/arxml.py
Add arxml reading vlan, frame_size, frames_endpoints, frames.receivers/transmitters, cycle_time...etc
> Improve arxml Ethernet Parameter reading

- src/canmatrix/formats/fibex.py
fix cases where the file name passed contains a part of the path.
> fix getting file name

- src/canmatrix/formats/xlsx.py
> implement folding excel again

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/arxml.py
1. Change E2E Dict into AutoSarE2E Class
2. Add AutoSarE2E SecOC Properties
3. Canmatrix.decode truncated/exceed modification
4. Read ETH Frame more capable
5. etc...
> Add support more ARXML AUTOSAR

- src/canmatrix/formats/fibex.py
Add Base-Data-Type and Category attributes for 32 bit length signals
> Add Base-Data-Type and Category attributes for 32 bit length signals

- src/canmatrix/formats/xlsx.py
should fix issue #768  and #541
> fix reading additionalFrameAttributes and additionalSignalAttributes

- src/canmatrix/formats/dbc.py
- tests/test_dbc.py
this should be an addon to pr #795
> fix dbc initial values (incl. tests)

- src/canmatrix/formats/fibex.py
Hi  @ebroecker  ,  I made a minor refactoring to address the missed condition. 
Please review this PR. 
Thank you.
> fix condition  of get base type in fibex

- src/canmatrix/canmatrix.py
> speedup for frame_by_id

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/ldf.py
some simple attempt to store multiple scalings per signal
> store multiple scalings per signal (LDF-import)

- src/canmatrix/formats/dbc.py
- tests/test_dbc.py
Hi all,
I added a proposal for parsing value tables of environment variables.
feedback appreciated
> parsing value tables of environment variables

- src/canmatrix/formats/eds.py
> further eds fix

- src/canmatrix/cli/convert.py
- src/canmatrix/formats/arxml.py
3.2.x is buggy and outdated
#813
> set autosar export t 4.1.0 by default
