ebroecker/canmatrix

- canmatrix/autosarhelper.py
- canmatrix/compare.py
- canmatrix/convert.py
- canmatrix/exportall.py
- canmatrix/importany.py
- canmatrix/importarxml.py
- canmatrix/importdbc.py
- canmatrix/importdbf.py
- canmatrix/importsym.py
- canmatrix/importxls.py
- canmatrix/log.py
In order to use the tools also within more complex workflows (e.g., piping results into another commandline tool), making status/debug message outputs configurable would be nice (e.g., disable the import warnings).
This change replaces print statements with categorized logging output (error, warn,
info, debug).
Output verbosity is configurable via command line switch (-s, -v, -vv).
Default level (no switch): only error/warn messages are printed
-s : (silent) only error messages are printed
-v : error/warn/info
-vv: error/warn/info/debug
*Warning* I was not able to test the change with all data formats.
> Configurable log output.

- canmatrix/convert.py
This change adds a command line flag (-f) to enforce the output format,
ignoring the output file extension.
This is eases the integration of canconvert into a diff tool (Beyond Compare).
Would be nice, if the functionality would be integrated into the main branch.
Thanks in advance!
Martin
Flag usage: -f <file extension> (with or without leading '.')
-f csv
f .csv
-f kcd
etc.
> (Optionally) enforce output format using command line flag.

- canmatrix/exportJson.py
Not every information required for parsing was present in the exported json file; also changed the signals into a list; not a dictionary with start bit string keys.
> Added all information required for decoding in the exported json file

- canmatrix/exportdbc.py
Exported DBC files with empty signal attributes failed on reimport. This is fixed by inserting quotation marks (`""`) for empty value strings.
(Error was: `NoneType object has no attribute group` because the regex doesn't match without the quotation marks, which is expected behaviour)
Also changed checking for empty `dict` by using [Python's ability to evaluate empty lists and dicts to `False`](https://docs.python.org/3.5/library/stdtypes.html#truth-value-testing). Feel free to reject this cosmetic alteration.
> export_fix: insert "" for empty string (exportDbc)

- canmatrix/importany.py
The `importany` functions returned a dict with the `CanMatrix` object as a value and an empty string as key. Now the option `key="my_canmatrix"`, if given, sets the key to `"my_canmatrix"`. If no `key` is given, behaviour remains unchanged.
> canmatrix.importany: accepts key for dict now

- canmatrix/exportall.py
- canmatrix/exportarxml.py
- canmatrix/exportfibex.py
- canmatrix/exportkcd.py
- canmatrix/exportxls.py
- canmatrix/exportxlsx.py
- canmatrix/exportyaml.py
- canmatrix/importall.py
- canmatrix/importarxml.py
- canmatrix/importkcd.py
- canmatrix/importxls.py
- canmatrix/importyaml.py
- setup.py
I made this pull request so that projects using this library only needs to specify which formats it needs to support instead of handling canmatrix own dependencies.
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies
> Improved dependency handling

- .travis.yml
- canmatrix/exportany.py
- test.sh
Since I assume Python 2.7 is still being supported, I think it's a good idea to have Travis test it also. I'm not sure if there was a particular reason for removing that before, but I'm trying to add it again with this pull request.
I also changed the procedure of installing canmatrix and its dependencies to use pip as that is the normal way to do it. This would make requirements.txt unnecessary but I have not deleted it in case it's used somewhere else.
> Reintroduce Travis testing Python 2.7

- canmatrix/dbc.py
Previously there was an issue with token parsing in the _BA section of DBC files. If the parser ran into a '[' or ']' within quotes then it would cough. This commit fixes this bug and allows the parser to work for these cases.
> Fix token parsing for BA_ section

- canmatrix/formats.py
- requirements.txt
- setup.py
Reduce logging level for unsupported formats at import and signal error on load/dump instead. Some formats may not need to be supported if never used.
YAML format only depends on [PyYAML](https://pypi.python.org/pypi/PyYAML), not [pyaml](https://pypi.python.org/pypi/pyaml).
Always depend on future since it can be installed on Python 3 as well without any conflicts.
> Changes for dependency handling

- canmatrix/dbc.py
Fix so that lines starting with _VAL and has no id are ignored
> Hotfix dbc botschaft id none digit

- canmatrix/kcd.py
There was an issue while converting dbf to kcd and no transmitter was present in nodeList.
While calculating the length of the transmitter an exception TypeError: object of type 'NoneType' has no len() was fired.
This commit fixes this bug by checking first if a transmitter or receiver is present in nodeList.
> Fix dbf to kcd TypeError: object of type 'NoneType' has no len()

- canmatrix/cmjson.py
Hello, I've noticed that when converting from dbc to json using --jsonExportAll each signal per message is present twice. I fixed it appending the signal one time less in the code, maybe it was a typo. I hope this can help!
Giuseppe
> Fix signals appended twice when converting from dbc to json

- canmatrix/canmatrix.py
`Signal.is_multiplexer` is calculated from the `multiplex` parameter.
So it shouldn't set from the parameters.
> `Signal.is_multiplexer` is a calculated value

- canmatrix/cmjson.py
When TextIOWrapper is garbage collected, it closes the raw stream unless the raw stream is detached first.
> Fix JSON dump closing file

- canmatrix/formats.py
fixes UnicodeDecodeErrorfor non-ascii strings
> apply encoding in formats.loads function for Python 2

- src/canmatrix/canmatrix.py
- src/canmatrix/cmcsv.py
- src/canmatrix/cmjson.py
- src/canmatrix/copy.py
- src/canmatrix/kcd.py
- src/canmatrix/sym.py
- src/canmatrix/xls.py
- src/canmatrix/xls_common.py
- src/canmatrix/xlsx.py
- test/test.dbc
- test/test_codec.py
Extend `--additionalFrameAttributes` to support any attribute name. Add this feature to json export. Replace `eval()` by `getattr()`.
> T196 fix additional frame

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
- test/test_codec.py
When playing with (yes, old) tests I found out some problems when mixing `decimal.Decimal` with `floats` ~~in single arithmetic operation. Also the converting back to int must be `round`, because `int(4.99999)` equals to 4, what is (I believe, and the old UTs also) not the wanted result.~~
The invalid (failing) tests are commented out for now.
I'll copy/move the reasonable old test to new test folder once I get a bit familiar with the pytest.
Regards
> Properly use 'decimal' in UTs

- src/canmatrix/dbf.py
BusMaster uses 'I' to denote signed signals, but not 'S'.
Thus conversion from DBC to DBF format is broken, but in opposite direction works just fine.
The PR fixes issue #207
> Fix import of signed signals from DBF files

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
I added a test to `test_canmatrix.py` that fails with the following error when decoding a float signal:
```
python /home/user/src/canmatrix/src/canmatrix/tests/test_canmatrix.py
Traceback (most recent call last):
File "/home/user/src/canmatrix/src/canmatrix/tests/test_canmatrix.py", line 133, in <module>
test_encode_decode_frame()
File "/home/user/src/canmatrix/src/canmatrix/tests/test_canmatrix.py", line 128, in test_frame_encode_decode
decoded_data = f1.decode(raw_bytes)
File "/home/user/src/canmatrix/src/canmatrix/canmatrix.py", line 890, in decode
signals_values[signal.name] = signal.raw2phys(value, decodeToStr)
File "/home/user/src/canmatrix/src/canmatrix/canmatrix.py", line 389, in raw2phys
value = value * self.factor + self.offset
TypeError: unsupported operand type(s) for *: …
```
> Fix frame decoding and encoding

- src/canmatrix/canmatrix.py
Fix comment indentation according to PEP 8 (block comment)
so that the block can be easily uncommented (ctrl+/), so that it looks better ...
no code change.
> Fix comment indentation (PEP8)

- src/canmatrix/canmatrix.py
The default should be False, otherwise the first signal is encoded twice and decoding fails. I would answer the question in the code `is it valid for None too?` with No.
The error was introduced probably by always applying the `multiplexSetter` in `__attrs_post_init__` in commit a8893523.
> Fix signal is_multiplexer being True by default

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
Add CanId tests and beautify str representation, it prints
```DA:0x01 PGN:0xABCD SA:0x02```
instead of
```DA:0X1 PGN:0XABCD SA:0X2```
> Add CanId tests. 

- src/canmatrix/arxml.py
- src/canmatrix/canmatrix.py
fix for missing "putSignalIntoFrame"
> [WIP] fix for #226

- src/canmatrix/__init__.py
- src/canmatrix/arxml.py
- src/canmatrix/canmatrix.py
- src/canmatrix/cmcsv.py
- src/canmatrix/compare.py
- src/canmatrix/convert.py
- src/canmatrix/copy.py
- src/canmatrix/dbc.py
- src/canmatrix/dbf.py
- src/canmatrix/formats.py
- src/canmatrix/log.py
- src/canmatrix/sym.py
- src/canmatrix/xls.py
- src/canmatrix/xlsx.py
- test/test.py
As discussed in #237, use module loggers based on module names and only configure logger in main(). It is intended to replace+finish #164.
* every logger is child of main "canmatrix" logger
* if used as a standalone converter/comparator, the 'canmatrix' logger is configured to provide all messages
* if used as a library, the logger setting is up to the user. He can either configure its root logger or use default config by calling `canmatrix.log.setup_logger()`. Or leave default `logging` behavior.
If you agree with this change, it would be gentle to document the above points somewhere, but I don't know where.
The rows
```
if __name__ == '__main__':
sys.exit(main())
```
in compare.py and convert.py don't work (at least due to import issues). It must be run using either examples/convert.py …
> Use module loggers.

- src/canmatrix/canmatrix.py
Unify attr.ib(factory=...) instead of longer default=attr.Factory(list) so that the whole file uses only single approach. No functional change.
Plus 3 changes - trailing spaces removed by pycharm - I'm not able not to commit them.
> Tidy: attrs factory for list and dict

- src/canmatrix/canmatrix.py
Remove spaces around '=' signs in attr.ib according to pep8 to decrease number of warning (currently only) in the IDE.
No code change.
> Tidy: pep8 fix spaces in attributes

- src/canmatrix/cmjson.py
- src/canmatrix/tests/test_cmjson.py
fixes 
* min and max for json import/export
* add tests for this
* remove import * from canmatrix
> add min and max to jsonAll export #275

- src/canmatrix/tests/test_arxml.py
- src/canmatrix/tests/test_canmatrix.py
- src/canmatrix/tests/test_cmjson.py
- src/canmatrix/tests/test_copy.py
- src/canmatrix/tests/test_dbc.py
- src/canmatrix/tests/test_frame_decoding.py
- src/canmatrix/tests/test_frame_encoding.py
- src/canmatrix/tests/test_utils.py
- src/canmatrix/tests/test_xls.py
If you agree with refactorings based on [Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/) , I did some cleanup in `tests` module.  It is based on pyCharm code inspect.
Changes:
- Snake_case for variables
- Two blank lines surround top-level functions
- Not shadow variable/function names
- Spaces around `=`
- Boolean values compared by `is`, not `==`
- Use `pytest` module to assert that exceptions is raised
- Remove unused imports
> Resolve inspect issues in tests module (pep8)

- src/canmatrix/canmatrix.py
- src/canmatrix/dbc.py
- src/canmatrix/dbf.py
- src/canmatrix/kcd.py
- src/canmatrix/tests/test_canmatrix.py
- src/canmatrix/xls.py
- src/canmatrix/xlsx.py
- test/createTestFdMatrix.py
- test/createTestMatrix.py
When merging the 'typing' branch I realized that some classes was unwillingly refactored to snake case.
> Make classes upper case again

- src/canmatrix/convert.py
- code style cleanup
- add annotations
- resolve issues reported by mypy. As the scope of a variable is "longer" than we're used from C languages, we can't mix `for frame in [string, frame, names]` and `for frame in [Frame(), Frame()]` within single function. Because once is the variable type assigned to string, next assignment of type Frame is reported as an (static typing) problem. Therefore I renamed some variables to distinguish between string and "object". But this is only "cosmetical detail".
> Tidy and annotate 'convert' module. Make mypy happy.

- mypy.ini
- src/canmatrix/cancluster.py
- src/canmatrix/canmatrix.py
- src/canmatrix/compare.py
- src/canmatrix/convert.py
- src/canmatrix/copy.py
- src/canmatrix/tests/test_canmatrix.py
- Try to decrease mypy warnings to minimum (CI would need to solve _all of them_)
- Plus some snake_case and BU removal
- Added some "help" to mypy config file
- I silenced (lot of) mypy warnings about "null pointers" - For example the `db.frame_by_name()` might return `None` but is never checked (maybe `raise` an exception instead of returning `None` in the future...)
- There are still about 17 mypy errors, mostly caused by float factory used as `converter`, and 3 real bugs in `compare` module (canmatrix\compare.py:296:8: error: "Frame" has no attribute "extended" ... @ebroecker could you check this please?).
- (And whole `formats` module is not checked yet)
Generally I already see benefits of the type annotations, mypy has actually pointed some bugs.
> Mypy cleanup

- src/canmatrix/canmatrix.py
i stumbled over these lines of code the other day as they throw an AttributeError as there was an misspelling in
`signal.receivers.remove(ecu.name)`
and i thought, maybe we should rely on _del_transmitter_ and _del_receiver_ to be consistent with _frame.update_receiver()_.
> - rely on del_transmitter and del_receiver

- src/canmatrix/formats/dbc.py
created a hashed list of frames to speedup the import process of dbc files, in my example i used a dbc file with 65k lines and around 800 frames.
before ...
```
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
50600    5.286    0.000    8.465    0.000 canmatrix.py:1390(frame_by_id)
25100584    3.180    0.000    3.180    0.000 canmatrix.py:600(__eq__)
1    0.452    0.452    9.610    9.610 canmatrix\formats\dbc.py:437(load)
110409    0.117    0.000    0.117    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
```
after ...
```
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.388    0.388    1.190    1.190 canmatrix\formats\dbc.py:437(load)
791    0.131    0.000    0.134    0.000 {built-in …
```
> hashed dbc import

- examples/exampleJoin.py
- src/canmatrix/canmatrix.py
- src/canmatrix/join.py
- src/canmatrix/tests/test_canmatrix.py
- src/canmatrix/utils.py
- Annotate and fix `join` module.
- Add `CanId` uses `ArbitrationId`.
- Add encoding header to some files.
It's the last unannotated file except of `formats`.
> Annotate and fix 'join' module. Update CanId.

- src/canmatrix/compare.py
- src/canmatrix/formats/yaml.py
Annotate, refactor (snake_case) and fix (old function names from `canmatrix` module) `compare` module.
There is still minor issue with accessing "protected" members of CompareResult. I'll try to attr.ibify the Compareresult in follow-up PR.
> Annotate and fix compare module

- src/canmatrix/formats/dbc.py
* arbitration_id instead of combound arbitration id was used in several cases
* ecu attribute definitions were not written, inspite signal attribute definitions were
written
> fix creating dbc files.

- src/canmatrix/formats/cmjson.py
Json format:
- fix/extend annotation
- rename variables to snake_case
- remove unused code (the `mode` variable)
- some list/dict comprehension (more mypy friendly)
- might collide with #338 but I started the branch already some weeks ago. I'll resolve it if needed.
> Json: annotation and cleanup, pep8

- src/canmatrix/__init__.py
- src/canmatrix/canmatrix.py
- Add explicit imports to `canmatrix.__init__`, still leaving the import * (to be deleted later when we decide, that the export list is enough). Note the mypy doesn't handle the `import *` correctly and produce false errors.
- Add converter function for `ArbitrationId`, because the classmethod converter is not supported by mypy and moreover the `from_compound_integer()` as converter effectively disallow the `Frame.arbitration_id` to be initialized directy by `ArbitrationId` instance.
all changes mainly targeted to reduce static typing issues.
> Explicit import in init and add some typing

- mypy.ini
- src/canmatrix/canmatrix.py
- src/canmatrix/formats/__init__.py
- src/canmatrix/formats/arxml.py
It is huge renaming hard to review but it was not possible to split to multiple PRs. I tried to rename functions so that they better describe the function objective. If you don't like them, feel free to say it.
I fixed few things when alternatively working with both `lxml.etree.Element` and `ArTree`. Also some small fixes related to renamings in Signal etc. All mypy reported issues in arxml are now indeed issues (`Signal` has no `_initValue` and line 1333 uses wrong data from xml)
Using the old tests I verified that the arxml->csv conversion produces identical result to at least somehow verify that it still works.
> Annotate and cleanup arxml

- src/canmatrix/formats/dbc.py
Finally the annotations for dbc format.
There is inconsistency in `add_signal_group()`, the `id` parameter is called as `int` from arxml and as `str` from dbc. I don't know what is correct. The function is currently annotated to accept numbers.
> Annotate and fix codestyle dbc

- src/canmatrix/formats/arxml.py
- src/canmatrix/formats/cmjson.py
- src/canmatrix/formats/sym.py
Remove is_little_endian comparicons with zero and one. (fix #326)
> Fix #326: Always use Signal.is_little_endian as bool

- src/canmatrix/join.py
Part of #323: remove redundant annotations from `join` module.
> Annotation cleanup "join" #323

- docs/cli.rst
Update cli doc (inspired by #361):
- remove `.py` from script names generated by setuptool
- explain how to run the module directly
Hope it will save some "how to" question in future.
> Update cli doc

- src/canmatrix/formats/xls.py
When loading xls, the arbitration id is misinterpeted by one character. This leads to wrong ids.
> fix: xls is using the wrong number for arbitration id

- src/canmatrix/formats/dbc.py
candb seems to be queasy about the order of the VFrameFormat attribute
definition. This Patch seems to generate a dbc, which can contain can_fd
AND J1939-frames.
> DBC: fix #242.

- requirements.txt
- src/canmatrix/cancluster.py
- src/canmatrix/canmatrix.py
- src/canmatrix/cli/compare.py
- src/canmatrix/cli/convert.py
- src/canmatrix/compare.py
- src/canmatrix/convert.py
- src/canmatrix/copy.py
- src/canmatrix/formats/__init__.py
- src/canmatrix/formats/arxml.py
- src/canmatrix/formats/csv.py
- src/canmatrix/formats/dbc.py
- src/canmatrix/formats/dbf.py
- src/canmatrix/formats/fibex.py
- src/canmatrix/formats/json.py
- src/canmatrix/formats/kcd.py
- src/canmatrix/formats/scapy.py
- src/canmatrix/formats/sym.py
- src/canmatrix/formats/xls.py
- src/canmatrix/formats/xls_common.py
- src/canmatrix/formats/xlsx.py
- src/canmatrix/formats/yaml.py
- src/canmatrix/j1939_decoder.py
- src/canmatrix/join.py
- src/canmatrix/log.py
- src/canmatrix/tests/test_canmatrix.py
- src/canmatrix/tests/test_cli_convert.py
- src/canmatrix/utils.py
- test/test.py
- Try to unify imports as described in #236
- Imports from `future` as recommended on [python-future](https://python-future.org/imports.html) pages
- Remove `from module import *` except of future (builtins)
- Let see what buildservers say...im not able to run in on py2
> [try to] Unify imports

- src/canmatrix/formats/fibex.py
* Fixed duplicate ids when two signals have same name in different frames
* Added CONNECTORS element
* Fixed location of PROCESSING-INFORMATION
* Added the bit length of each signal
> Fix some bugs in FIBEX export

- requirements.test.py3.txt
- src/canmatrix/cli/convert.py
- src/canmatrix/formats/csv.py
- src/canmatrix/formats/json.py
- src/canmatrix/formats/xls.py
- src/canmatrix/formats/xlsx.py
- src/canmatrix/tests/test_json.py
Issue with jsonExportAll (#441) is already fixed, but there are similar issues with jsonExportCanard and additionalSignalAttributes.
I think it's better to pass the full CLI option name to prevent such confusion in the future.
> Repair more click convert parameters

- src/canmatrix/formats/dbc.py
Fixes the following issue we see for python 3.8 during testing:
for env_var_name, env_var in db.env_vars.items():
E   RuntimeError: dictionary keys changed during iteration
> Fixing issue where we see dictionary attributes change during iteration

- src/canmatrix/formats/sym.py
- src/canmatrix/tests/test_sym.py
I have added a fix for #465 and a new test case in test_sym.py that checks for an EOFError in the case of an untemrinated enum.
> Check for EOF when parsing enums in a .sym file. Fixes #465

- src/canmatrix/formats/__init__.py
As mentioned in the ticket itself, this alters the _level_ the message is logged to: instead of logging to `INFO`, it is now logged as `ERROR`.
> #459: Log the exception as well when importing a format failed

- src/canmatrix/canmatrix.py
- src/canmatrix/j1939_decoder.py
- src/canmatrix/tests/test_canmatrix.py
- src/canmatrix/tests/test_j1939_decoder.py
Fixes #474 
Remove the criteria that PF must be >= 240 for PS field to be set as
this seems to be incorrect. (It may be that for some specific case the
PS need to not be used, but it isn't documented here and in general the
PGN should be all 18 bits)
Modifed Tests:
test_canmatrix_get_frame_by_pgn()
seemed to be using made up data and didn't account for the DP and EDP
fields in expected PGN
test_canid_repr()
Modified the expected repr value to include the PS field in the PGN.
test_canid_parse_values()
Modified expected PGN to include the PS field, Moved the list of
test_data into parametrized cases on a new test.
New Tests:
test_frame_j1939_id_from_components()
Tests constructing a full 29-bit CAN ID from the Priority, Source, and
PGN
test_frame_decode_j1939_id()
Tests extracting Priority …
> Fix J1939 PGN getter/setter to use full 18bits. Fixes #474

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
Changed default arbitration_id.extended to False from None
Removed the existing equals method and using attr.s default comparison methods
The current logic implemented is that:
ArbitrationId(id=0x1, extended=False) <   ArbitrationId(id=0x1, extended=True)
ArbitrationId(id=0x1, extended=True) < ArbitrationId(id=0x2, extended=False)
> Adding changes to allow ArbitrationId classes to be sorted

- src/canmatrix/formats/sym.py
- src/canmatrix/tests/test_sym.py
fixes #480 
Fix sym.dump to export the value_table into the {ENUMS} field of the.sym file.
Refactor to remove the use of global variables "enum_dict" and "enums"
Add a test which checks that enums in the original .sym file and enums
which appear as values on a signal are exported to the .sym file.
> Fix sym.dump to export the value_table

- src/canmatrix/formats/sym.py
- src/canmatrix/tests/test_sym.py
Fixes an oversight in my previous fix for #480 
Add the values from signals which are in multiplexed frames as well.
> Fix additional case in sym enum export

- src/canmatrix/formats/__init__.py
Logging as exception prints a stack backtrace. Since the modules are optional and listed as extra instead of a required dependency, this should probably be a warning instead of an error/exception.
Just run the tests included in this module, without installing additional modules (such as `xlsxwriter`):
```
pip3 install canmatrix
python3 test/test.py
```
```
arxml is not supported
Traceback (most recent call last):
File "/home/user/.local/lib/python3.8/site-packages/canmatrix/formats/__init__.py", line 27, in <module>
importlib.import_module("canmatrix.formats." + module)
File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen …
```
> Log missing format module import as warning instead of exception

- src/canmatrix/formats/json.py
- src/canmatrix/tests/test_json.py
fd flag is implemented but not used in json.
add is_fd flag to the json exporter.
> add is_fd flag for json output

- src/canmatrix/compare.py
When comparing two dbc, the the frame has different ID it should be marked as "changed" frame.
> Correctly the result if compare two frame with different ID

- requirements.txt
- setup.py
- src/canmatrix/canmatrix.py
DeprecationWarning: The usage of `cmp` is deprecated and will be removed
on or after 2021-06-01.  Please use `eq` and `order` instead.
@attr.s(cmp=False)
Signed-off-by: An Nguyen <phucan.nguyen@daum.net>
> fix issue #547

- src/canmatrix/compare.py
If the frame has same ID but different name, it should get data from frame_by_id() instead of frame_by_name() for comparison.
> fix issue #559

- src/canmatrix/canmatrix.py
- src/canmatrix/tests/test_canmatrix.py
use min value when initial_value default value is out of range [min, max]
> fix initial value setting

- src/canmatrix/formats/arxml.py
- src/canmatrix/formats/dbc.py
- src/canmatrix/tests/test_arxml.py
Hello,
Using iSignalName for signal naming in arxml parser
I think this is aligned with Vector
added new attributes for signal names (ShortName, compuName), so if any other user have preference for naming (my personal preference is the compu method name)
I think older versions of canmatrix used the compu name, so I may be wrong with this PR
thanks
> [arxml]: canmatrix.Signal names rework

- docs/cli.rst
- src/canmatrix/canmatrix.py
- src/canmatrix/cli/convert.py
- src/canmatrix/convert.py
- src/canmatrix/formats/arxml.py
- src/canmatrix/tests/test_arxml.py
- src/canmatrix/tests/test_frame_decoding.py
- src/canmatrix/utils.py
Add a converter from PDU contained to multiplexed frame
Add option to handle it in the CLI
Update decoder function
> rework arxml parsing and use Pdu for PDU contained frames

- src/canmatrix/formats/json.py
This extra output lets us recover the full signal tree for extended multiplexing.
> Improve multiplexer JSON output

- src/canmatrix/cli/convert.py
It looks like line 88 was copied from line 87, but while editing '--no-arxmlFlexray' was not updated.
I have simply changed --no-arxmlFlexray to --no-arxmlEthernet
@ebroecker
> Fix typo in cli/convert.py file

- src/canmatrix/formats/arxml.py
to get the signals for a pdu you have to use follow_all_ref instead of follow_ref
> bugfix: list of signals are always empty (in a PDU)

- src/canmatrix/canmatrix.py
- src/canmatrix/cli/convert.py
- src/canmatrix/convert.py
Referring to **Issue#610**
when converting with --deleteObsoleteDefines switch,  custom attributes are removed in the output DBC though atleast one of the signal in the dbc has the custom attribute. We can test this by running 
`python3 ./convert.py  --deleteObsoleteDefines  ./InputDBC.dbc ./OutputDBC.dbc` from the examples folder.
Moving the else condition to refer to the signal iterator for loop solves this issue. Feel free to update if this is not the intended solution.
> Kankan patch :: Custom Signal Attributes are removed 

- src/canmatrix/utils.py
add a conversion of 0b and 0x string values into int string representation in the guess_value method
initial motivation was to get valid input values for the decimal.Decimal() class
since it crashed in the arxml.py file line 1234:
1232            if initvalue is not None and initvalue.text is not None:
1233                initvalue.text = canmatrix.utils.guess_value(initvalue.text)
1234               new_signal.initial_value = float_factory(initvalue.text)
i discovered the "decode_number" function as well but was not sure if the intention of the "guess_value" was to return a string always.
> Update guess_value method in utils.py

- src/canmatrix/canmatrix.py
- src/canmatrix/cli/convert.py
- src/canmatrix/convert.py
Added below functions to the canconvert script , which we found useful in maintaining database.
1. **deleteFloatingSignals**  : Unassigned signals to a frame/message will be deleted.
2. **checkFloatingFrames** : CAN message/frame without sender node will be warned
3. **checkSignalRange** : Signals consisting raw min/max value set to 0 will be warned
4. **checkSignalUnit** : Signals without units and value table will be warned.
5. **checkSignalReceiver** : Signals without an assigned Receiver will be warned
6. **checkFloatingSignals** : Unassigned signals to a frame/message will be warned
> Adding Few Check functions 

- src/canmatrix/formats/arxml.py
bug since commit 97ebe53c66556410d9484f7335c6702f24c19b5f
the float_factory - doesn't matter if Deciaml() or float() is used - does not have a base-argument like int()
> bugfix float_factory: there is no base-argument

- src/canmatrix/formats/arxml.py
bug since commit d2fbdaae8ef622deff26054bfa497c55ff30779d
before commit d2fbdaae8ef622deff26054bfa497c55ff30779d for each port in port_frames the ecu was checked and added as receiver or transmitter.
after (bug) only the first comm_direction was added as receiver or transmitter, the remaining ones are missed in the list of receivers/transmitters.
> bugfix: get all receivers/transmitters and not only one

- src/canmatrix/formats/xlsx.py
startbit will be up to 512 in canfd, and sorting signals should in right bit numbering condition.
> fix signals sort

- src/canmatrix/formats/scapy.py
`extended` is not formatted as a   string, which results in python trying to resolve this non-existing object.
I have tested that this fixes the scapy import and actually works for extended CAN IDs.
This commit fixes #677
> bugfix: set flags as string in scapy export

- setup.py
- src/canmatrix/canmatrix.py
Commit 46d4de4 (#700) breaks compatibility with any Python version below 3.8. 
This fixes this issue by using `importlib-metadata` for those versions.
> Fix importlib.metadata issue on Python 3.7

- src/canmatrix/formats/arxml.py
- src/canmatrix/tests/ARXMLSecuredPDUTest.arxml
This is trying to avoid exceptions like the following when the selector can't find matches. 
```
AttributeError: 'NoneType' object has no attribute 'sourceline'
```
> Filter out None results in selector

- src/canmatrix/formats/arxml.py
Log SecuredIPdus without Payload and keep processing frames.
> Ignore SecuredIPdus with no Payload

- src/canmatrix/formats/__init__.py
This commit spares the user from seeing **all** unsupported formats printed in the console when running canconvert or cancompare or just `import canmatrix` or using another package (like asammdf) which has a dependency on canmatrix. 
If a user tries to use a format that is not supported for them, an error will be logged saying that format is not supported, and that I think should be enough.
> Log unsupported formats as debug instead of warning

- src/canmatrix/formats/arxml.py
This change adds the data_length to the E2E transformer configuration.
> Add data length to signal group's E2E transformer configuration

- src/canmatrix/formats/fibex.py
The main idea is to avoid having the same default name `clusterShort` for the clusters created when converting a dbc to a fibex file.
> add a suffix containing file name in cluster name

- src/canmatrix/canmatrix.py
The factor of the signal could be zero and it makes an other error with dividing by zero so when the factor equals zero, we should set it to default value (factor=1)
> canmatrix: fix the factor could be zero

- src/canmatrix/formats/arxml.py
Under the tag DATA-CONSTR could have PHYS-CONSTRS and INTERNAL-CONSTRS in one DATA-CONSTR-RULE and could be have more than one tag DATA-CONSTR-RULE, with current logic, we only use the LOWER-LIMIT and UPPER-LIMIT of the tag INTERNAL-CONSTRS so I modify a little to make it get the lowest internal constr value and biggest internal constr value to lower/upper variables
> arxml: Only get min/max of the INTERNAL-CONSTR

- setup.py
- src/canmatrix/canmatrix.py
PR #744 broke Python 2.7 support. Can we go on and remove the remaining hybridation ?
(greetings)
https://github.com/ebroecker/canmatrix/pull/744/files
https://github.com/ebroecker/canmatrix/issues/742
> remove six usage

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/dbc.py
The previous code used the db's GenSigStartValue as the default value for all signals.  That should only be used if an individual signal doesn't have a GenSigStartValue.  This fixes signal's losing their GenSigStartValue after a dbc merge.  Sometimes it would cause the GenSigStartValue to be outside of the min / max value.
Also specifically imported Optional so the code would run in Python 3.12.
> Use individual signal's "GenSigStartValue" as default value when merging dbc files

- src/canmatrix/formats/fibex.py
@ebroecker , Regarding the CAN FD in DBC 
canmatrix does read this property from the DBC and populate the "is_fd" proeprty 
The code in canmatrix that writes back FIBEX, does not take it into consideration
> fix can fd in fibex

- src/canmatrix/canmatrix.py
- src/canmatrix/formats/dbc.py
- tests/test_dbc.py
I noticed that the code didn't handle simple multiplexing quite as expected so I added in code to support simple multiplexing and add the multiplexor to the signals in the frame when needed
> Add in simple multiplexing for dbc

- src/canmatrix/formats/fibex.py
@ebroecker ,  based on the specification , once SIG_VALTYPE is  1 or 2 it's float , this need to be fixed in fibex
> fix base type once Signal is float in Fibex

- examples/BusmasterRestbus.py
- src/canmatrix/__init__.py
- src/canmatrix/cancluster.py
- src/canmatrix/cli/compare.py
- src/canmatrix/cli/convert.py
- src/canmatrix/compare.py
- src/canmatrix/convert.py
- src/canmatrix/copy.py
- src/canmatrix/formats/__init__.py
- src/canmatrix/formats/arxml.py
- src/canmatrix/formats/csv.py
- src/canmatrix/formats/dbc.py
- src/canmatrix/formats/dbf.py
- src/canmatrix/formats/fibex.py
- src/canmatrix/formats/json.py
- src/canmatrix/formats/kcd.py
- src/canmatrix/formats/ldf.py
- src/canmatrix/formats/odx.py
- src/canmatrix/formats/scapy.py
- src/canmatrix/formats/sym.py
- src/canmatrix/formats/xls.py
- src/canmatrix/formats/xls_common.py
- src/canmatrix/formats/xlsx.py
- src/canmatrix/formats/yaml.py
- src/canmatrix/j1939_decoder.py
- src/canmatrix/join.py
- src/canmatrix/log.py
- src/canmatrix/utils.py
- tests/createTestMatrix.py
- tests/test.py
this is a follow up to my previous PR's
> remove more Python2 hybridation

- src/canmatrix/formats/json.py
Only recently noticed I missed this in my last contribution to this importer.
> fix: json import attributes at the frame level
